# Generated by Django 4.2.20 on 2025-04-06 21:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('latitude', models.FloatField(editable=False)),
                ('longitude', models.FloatField(editable=False)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
