# Generated by Django 4.2.20 on 2025-04-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dispositivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
