# Generated by Django 4.2.20 on 2025-04-27 20:50

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dispositivo', '0002_alter_dispositivo_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='longitude',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='localizacao',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, null=True, srid=4326),
        ),
    ]
