# Generated by Django 4.2.20 on 2025-05-29 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dispositivo', '0003_remove_dispositivo_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dispositivo',
            table='dispositivo',
        ),
    ]
