# Generated by Django 4.2.20 on 2025-05-29 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dados_Climaticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dadoclimatico',
            table='dado_climatico',
        ),
    ]
