# Generated by Django 4.2.20 on 2025-05-18 18:40

from django.db import migrations
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Dados_Climaticos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoclimatico',
            name='time',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='1 day', null=True),
        ),
    ]
