# Generated by Django 4.2.20 on 2025-05-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dados_Climaticos', '0002_dadoclimatico_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadoclimatico',
            name='time',
        ),
    ]
