# Generated by Django 4.2.20 on 2025-07-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dispositivo', '0004_alter_dispositivo_table'),
        ('Dados_Climaticos', '0002_alter_dadoclimatico_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoclimatico',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Dispositivo.dispositivo'),
        ),
    ]
