# Generated by Django 4.2.20 on 2025-05-18 19:00

from django.db import migrations
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Dados_Climaticos', '0003_remove_dadoclimatico_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoclimatico',
            name='time',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='1 day', null=True),
        ),
    ]
