# Generated by Django 4.2.20 on 2025-05-29 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Direcao_Vento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='direcaovento',
            table='direcao_vento',
        ),
    ]
